baseURL = 'https://soukainaouakka.netlify.app'
languageCode = 'en-us'
theme = 'graysx'
title = 'Soukaina'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
address = "PARIS, FRANCE"
email = "Ouakkasoukaina@gmail.com"
phone = "(+33) 7 83 49 30 15"

# Socials

twitter = "https://www.linkedin.com/in/soukaina-ouakka"
facebook = "https://www.linkedin.com/in/soukaina-ouakka"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04